spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ticket_sys?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    druid数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:    #默认为空
  # spirng 缓存管理参数配置
  cache:
    redis:
      time-to-live: 500000
  #定义时间的json序列化格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: "GMT+8"

#    type: SIMPLE

#配置Mybatis的相关属性
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml #指定mapper XML文件的位置
  type-aliases-package: com.javaee.ticketsys.model  #指定实体类的别名的映射路径

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印输出SQL语句
    map-underscore-to-camel-case: true   # 启动驼峰式转换
    use-generated-keys: true      #开启自增组件
#debug: true

server:
  port: 9000

