version: '3'
services:
  mysql8:
    image: mysql
    container_name: mysql
    volumes:
      - /Users/huaiwen/data:/var/lib/mysql
      - /Users/huaiwen/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
  ubuntu:
    image: ubuntu
    container_name: ubuntu1
    
