# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://192.168.45.130:3306/teaching_sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      #      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #      timeBetweenEvictionRunsMillis: 60000
      #      # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      minEvictableIdleTimeMillis: 300000
      #      # 配置一个连接在池中最大生存的时间，单位是毫秒
      #      maxEvictableIdleTimeMillis: 900000

      #配置Mybatis的相关属性
mybatis:
  mapper-locations: classpath:mapper/*.xml #指定mapper XML文件的位置
  type-aliases-package: com.javaee.mybatis.relations.domain  #指定实体类的别名的映射路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印输出SQL语句
    map-underscore-to-camel-case: true   # 启动驼峰式转换
    use-generated-keys: true      #开启自增组件